### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein
### GitHub Corrected URLs

| Was | Now |
| --- | --- |
| https://github.com/forhappy/A-Detailed-Cplusplus-Concurrency-Tutorial | https://github.com/forhappy/Cplusplus-Concurrency-In-Practice |
| https://github.com/swaroopch/byte_of_python | https://github.com/swaroopch/byte-of-python |
| https://github.com/the-teacher/cocktails_for_programmers | https://github.com/cocktails-for-programmers/cocktails_for_programmers |
### HTTPS Corrected URLs

| Was | Now |
| --- | --- |
| http://addyosmani.com/resources/essentialjsdesignpatterns/book/ | https://addyosmani.com/resources/essentialjsdesignpatterns/book/ |
| http://docs.travis-ci.com/ | https://docs.travis-ci.com/ |
| http://en.wikipedia.org/wiki/Category:Wikipedia_books_%28community_books%29 | https://en.wikipedia.org/wiki/Category:Wikipedia_books_%28community_books%29 |
| http://guides.emberjs.com/v2.0.0/ | https://guides.emberjs.com/v2.0.0/ |
| http://learnxinyminutes.com/ | https://learnxinyminutes.com/ |
### Other Corrected URLs

| Was | Now |
| --- | --- |
| http://bonsaiden.github.com/JavaScript-Garden | http://bonsaiden.github.io/JavaScript-Garden/ |
| http://mislav.uniqpath.com/poignant-guide/book/ | http://poignant.guide/book/ |
| http://rustforrubyists.com/ | http://www.rustforrubyists.com |
| http://sphinx-doc.org/contents.html | http://www.sphinx-doc.org/en/stable/contents.html |
| http://twitter.github.com/effectivescala | http://twitter.github.io/effectivescala/ |
| http://www.rxmarbles.com | http://rxmarbles.com/ |
| https://code.google.com/p/thinkstats | https://code.google.com/p/thinkstats/ |
| https://www.packer.io/docs | https://www.packer.io/docs/ |

### CODE REVIEW

**Comment by raccoonyy** [comment]
:clap: 

Good job~!

Would you please correct below links?

Rust For Rubyists
http://www.rustforrubyists.com -> https://github.com/steveklabnik/rust_for_rubyists

Think Stats
https://code.google.com/p/thinkstats/ -> https://github.com/AllenDowney/ThinkStats2

**Comment by ReadmeCritic** [comment]
Yup hold on

**Comment by ReadmeCritic** [comment]
@raccoonyy ready

**Comment by raccoonyy** [comment]
Thanks for your commit!

**Comment by raccoonyy** [comment]
Thanks for your commit!

:+1:

**Comment by ReadmeCritic** [comment]
:tada:

**Pull request merged**
